export interface Pattern {
  name: string;
  description: string;
  cells: [number, number][]; // [row, col] coordinates
}

export const PATTERNS: Pattern[] = [
  {
    name: "Glider",
    description: "Moves diagonally across the grid",
    cells: [
      [0, 1],
      [1, 2],
      [2, 0],
      [2, 1],
      [2, 2],
    ],
  },
  {
    name: "Blinker",
    description: "Oscillates between two states (period 2)",
    cells: [
      [0, 0],
      [0, 1],
      [0, 2],
    ],
  },
  {
    name: "Toad",
    description: "Oscillates with period 2",
    cells: [
      [0, 1],
      [0, 2],
      [0, 3],
      [1, 0],
      [1, 1],
      [1, 2],
    ],
  },
  {
    name: "Beacon",
    description: "Oscillates with period 2",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [2, 2],
      [2, 3],
      [3, 2],
      [3, 3],
    ],
  },
  {
    name: "Pulsar",
    description: "Oscillates with period 3",
    cells: [
      [0, 2],
      [0, 3],
      [0, 4],
      [0, 8],
      [0, 9],
      [0, 10],
      [2, 0],
      [2, 5],
      [2, 7],
      [2, 12],
      [3, 0],
      [3, 5],
      [3, 7],
      [3, 12],
      [4, 0],
      [4, 5],
      [4, 7],
      [4, 12],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 8],
      [5, 9],
      [5, 10],
      [7, 2],
      [7, 3],
      [7, 4],
      [7, 8],
      [7, 9],
      [7, 10],
      [8, 0],
      [8, 5],
      [8, 7],
      [8, 12],
      [9, 0],
      [9, 5],
      [9, 7],
      [9, 12],
      [10, 0],
      [10, 5],
      [10, 7],
      [10, 12],
      [12, 2],
      [12, 3],
      [12, 4],
      [12, 8],
      [12, 9],
      [12, 10],
    ],
  },
  {
    name: "Block",
    description: "Still life: remains unchanged",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
    ],
  },
  {
    name: "Beehive",
    description: "Still life: remains unchanged",
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 2],
    ],
  },
  {
    name: "Loaf",
    description: "Still life: remains unchanged",
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 3],
      [3, 2],
    ],
  },
  {
    name: "Boat",
    description: "Still life: remains unchanged",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },
  {
    name: "LWSS",
    description: "Lightweight spaceship - moves horizontally",
    cells: [
      [0, 1],
      [0, 4],
      [1, 0],
      [2, 0],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [2, 4],
    ],
  },
  {
    name: "Pentomino",
    description: "Creates interesting patterns",
    cells: [
      [0, 1],
      [1, 1],
      [1, 2],
      [2, 0],
      [2, 1],
    ],
  },
];
