export type PatternType = 'still-life' | 'oscillator' | 'spaceship' | 'methuselah' | 'replicator' | 'other';

export interface Pattern {
  name: string;
  description: string;
  cells: [number, number][]; // [row, col] coordinates
  ruleset?: string; // Optional ruleset notation (e.g., 'B36/S23')
  type: PatternType; // Pattern category
}

export const PATTERNS: Pattern[] = [
  {
    name: "Glider",
    description: "Moves diagonally across the grid",
    type: "spaceship",
    cells: [
      [0, 1],
      [1, 2],
      [2, 0],
      [2, 1],
      [2, 2],
    ],
  },
  {
    name: "Blinker",
    description: "Oscillates between two states (period 2)",
    type: "oscillator",
    cells: [
      [0, 0],
      [0, 1],
      [0, 2],
    ],
  },
  {
    name: "Toad",
    description: "Oscillates with period 2",
    type: "oscillator",
    cells: [
      [0, 1],
      [0, 2],
      [0, 3],
      [1, 0],
      [1, 1],
      [1, 2],
    ],
  },
  {
    name: "Beacon",
    description: "Oscillates with period 2",
    type: "oscillator",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [2, 2],
      [2, 3],
      [3, 2],
      [3, 3],
    ],
  },
  {
    name: "Pulsar",
    description: "Oscillates with period 3",
    type: "oscillator",
    cells: [
      [0, 2],
      [0, 3],
      [0, 4],
      [0, 8],
      [0, 9],
      [0, 10],
      [2, 0],
      [2, 5],
      [2, 7],
      [2, 12],
      [3, 0],
      [3, 5],
      [3, 7],
      [3, 12],
      [4, 0],
      [4, 5],
      [4, 7],
      [4, 12],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 8],
      [5, 9],
      [5, 10],
      [7, 2],
      [7, 3],
      [7, 4],
      [7, 8],
      [7, 9],
      [7, 10],
      [8, 0],
      [8, 5],
      [8, 7],
      [8, 12],
      [9, 0],
      [9, 5],
      [9, 7],
      [9, 12],
      [10, 0],
      [10, 5],
      [10, 7],
      [10, 12],
      [12, 2],
      [12, 3],
      [12, 4],
      [12, 8],
      [12, 9],
      [12, 10],
    ],
  },
  {
    name: "Block",
    description: "Still life: remains unchanged",
    type: "still-life",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
    ],
  },
  {
    name: "Beehive",
    description: "Still life: remains unchanged",
    type: "still-life",
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 2],
    ],
  },
  {
    name: "Loaf",
    description: "Still life: remains unchanged",
    type: "still-life",
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 3],
      [3, 2],
    ],
  },
  {
    name: "Boat",
    description: "Still life: remains unchanged",
    type: "still-life",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },
  {
    name: "LWSS",
    description: "Lightweight spaceship - moves horizontally",
    type: "spaceship",
    cells: [
      [0, 1],
      [0, 4],
      [1, 0],
      [2, 0],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [2, 4],
    ],
  },
  {
    name: "Pentomino",
    description: "Creates interesting patterns",
    type: "methuselah",
    cells: [
      [0, 1],
      [1, 1],
      [1, 2],
      [2, 0],
      [2, 1],
    ],
  },
  // HighLife patterns (B36/S23)
  {
    name: "Replicator",
    description: "HighLife: Self-replicates to create copies (period 6)",
    type: "replicator",
    ruleset: "B36/S23",
    cells: [
      [0, 0],
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 2],
      [2, 0],
      [2, 1],
      [2, 2],
    ],
  },
  {
    name: "Bomber",
    description: "HighLife: Creates debris while moving",
    type: "spaceship",
    ruleset: "B36/S23",
    cells: [
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 2],
      [2, 3],
    ],
  },
  // Day & Night patterns (B3678/S34678)
  {
    name: "Diamond",
    description: "Day & Night: Oscillates creating diamond shapes (period 2)",
    type: "oscillator",
    ruleset: "B3678/S34678",
    cells: [
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },
  {
    name: "Inverter",
    description: "Day & Night: Switches on/off states",
    type: "other",
    ruleset: "B3678/S34678",
    cells: [
      [0, 0],
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 2],
      [2, 0],
      [2, 1],
      [2, 2],
    ],
  },
  // Seeds patterns (B2/S)
  {
    name: "Two Seeds",
    description: "Seeds: Explosive expanding pattern",
    type: "other",
    ruleset: "B2/S",
    cells: [
      [0, 0],
      [0, 1],
    ],
  },
  // Maze patterns (B3/S12345)
  {
    name: "Maze Seed",
    description: "Maze: Small seed that grows into maze structures",
    type: "other",
    ruleset: "B3/S12345",
    cells: [
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },
  // Coral patterns (B3/S45678)
  {
    name: "Coral Seed",
    description: "Coral: Grows slowly into coral-like formations",
    type: "other",
    ruleset: "B3/S45678",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
      [2, 2],
    ],
  },
  // Replicator patterns (B1357/S1357)
  {
    name: "Square",
    description: "Replicator: Square that replicates diagonally",
    type: "replicator",
    ruleset: "B1357/S1357",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
    ],
  },
  // Life Without Death patterns (B3/S012345678)
  {
    name: "Expander",
    description: "Life Without Death: Continuously expands outward",
    type: "other",
    ruleset: "B3/S012345678",
    cells: [
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },
  // Move patterns (B368/S245)
  {
    name: "Mover",
    description: "Move: Pattern that slides across the grid",
    type: "spaceship",
    ruleset: "B368/S245",
    cells: [
      [0, 0],
      [0, 1],
      [1, 1],
      [1, 2],
      [2, 0],
      [2, 2],
    ],
  },
  // Diamoeba patterns (B35678/S5678)
  {
    name: "Amoeba",
    description: "Diamoeba: Creates chaotic diamond-shaped patterns",
    type: "other",
    ruleset: "B35678/S5678",
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 0],
      [2, 3],
      [3, 1],
      [3, 2],
    ],
  },
];

export const PATTERN_TYPE_LABELS: Record<PatternType, string> = {
  'still-life': 'Still Lifes',
  'oscillator': 'Oscillators',
  'spaceship': 'Spaceships',
  'methuselah': 'Methuselahs',
  'replicator': 'Replicators',
  'other': 'Other'
};
